run:
  timeout: 3m
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - testifylint
    - nolintlint
    - bodyclose
    - goimports
    - importas
    - ireturn
linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  testifylint:
    enable-all: true
  nolintlint:
    require-explanation: true
    require-specific: true
