apiVersion: v1
kind: Service
metadata:
  name: spegel
spec:
  clusterIP: "None"
  selector:
    name: spegel
  ports:
    - name: registry
      protocol: TCP
      port: 5000
      targetPort: registry
