apiVersion: v1
kind: Service
metadata:
  name: spegel
spec:
  selector:
    name: spegel
  ports:
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: spegel-headless
spec:
  clusterIP: "None"
  selector:
    name: spegel
  ports:
    - name: registry
      protocol: TCP
      port: 5000
      targetPort: registry
