name: Feature Request
description: Suggest a new feature for Spegel
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a feature request! Please check existing issues before submitting.
  - type: textarea
    attributes:
      label: Describe the problem to be solved
      description: A clear description of the problem that needs to be addressed by this feature request. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution to the problem
      description: A clear description of the solution or multiple possible solutions to implement this feature request.
    validations:
      required: false
