apiVersion: v1
kind: Service
metadata:
  name: {{ include "spegel.fullname" . }}
  labels:
    {{- include "spegel.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "spegel.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spegel.fullname" . }}-headless
  labels:
    {{- include "spegel.labels" . | nindent 4 }}
spec:
  clusterIP: "None"
  selector:
    {{- include "spegel.selectorLabels" . | nindent 4 }}
  ports:
    - name: registry
      port: {{ .Values.service.registry.port }}
      targetPort: registry
      protocol: TCP
