name: e2e
on:
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Dockerfile"
      - "test/**"
      - "charts/**"
jobs:
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cni: [iptables, iptables-ipv6, ipvs]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run e2e
        run: make e2e CNI=${{ matrix.cni }}
